import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  gradient: {
    flex: 1,
    backgroundColor: '#18181b',
  },
  container: {
    paddingHorizontal: 24,
    paddingBottom: 24,
    backgroundColor: 'transparent',
  },
  centered: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  topSpacer: {
    height: 36,
  },
  searchBarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  searchBar: {
    flex: 1,
    backgroundColor: '#23232b',
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingVertical: 12,
    marginRight: 12,
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    borderWidth: 1,
    borderColor: '#2d2d34',
  },
  searchInput: {
    fontSize: 18,
    color: '#fff',
    letterSpacing: 0.5,
  },
  profileCircle: {
    width: 48,
    height: 48,
    backgroundColor: '#23232b',
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#6366f1',
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  profileEmoji: {
    fontSize: 32,
    textAlign: 'center',
    color: '#fff',
    textShadowColor: '#6366f1',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  tabsRow: {
    marginBottom: 28,
  },
  tabsContainer: {
    flexDirection: 'row',
    gap: 8,
  },
  tab: {
    borderRadius: 18,
    marginRight: 8,
    overflow: 'hidden',
    minWidth: 70,
    backgroundColor: '#23232b',
    borderWidth: 1,
    borderColor: '#2d2d34',
  },
  tabGradient: {
    paddingVertical: 8,
    paddingHorizontal: 18,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabSelected: {
    // handled by tabGradient
  },
  tabText: {
    color: '#e5e7eb',
    fontWeight: 'bold',
    fontSize: 16,
    paddingVertical: 8,
    paddingHorizontal: 18,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  tabTextSelected: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
    textAlign: 'center',
    textShadowColor: '#6366f1',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
    letterSpacing: 0.5,
  },
  section: {
    marginBottom: 32,
    backgroundColor: 'transparent',
  },
  noEventsContainer: {
    alignItems: 'center',
    marginTop: 40,
  },
  noEventsText: {
    color: '#a1a1aa',
    fontSize: 18,
    textAlign: 'center',
    fontWeight: '600',
    marginBottom: 8,
  },
  noEventsSubtext: {
    color: '#71717a',
    fontSize: 14,
    textAlign: 'center',
  },
  cardGradient: {
    borderRadius: 18,
    marginBottom: 28,
    shadowColor: '#6366f1',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
  },
  youtubeCard: {
    backgroundColor: '#18181b',
    borderRadius: 18,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
  },
  youtubeCardImage: {
    width: '100%',
    height: 180,
    backgroundColor: '#23232b',
  },
  placeholderImage: {
    width: '100%',
    height: 180,
    backgroundColor: '#23232b',
    alignItems: 'center',
    justifyContent: 'center',
  },
  placeholderText: {
    fontSize: 48,
    color: '#a1a1aa',
    marginBottom: 8,
  },
  placeholderCategory: {
    fontSize: 16,
    color: '#ec4899',
    fontWeight: '600',
  },
  youtubeCardContent: {
    padding: 16,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  youtubeCardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
    flex: 1,
    marginRight: 12,
    textShadowColor: '#6366f1',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  bookedBadge: {
    backgroundColor: '#10b981',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  bookedBadgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  descRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  youtubeCardDesc: {
    color: '#e5e7eb',
    fontSize: 14,
    opacity: 0.85,
    flex: 1,
    marginRight: 12,
  },
  arrowCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  arrowGradientCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
  },
  arrowText: {
    fontSize: 20,
    color: '#fff',
    fontWeight: 'bold',
    textShadowColor: '#ec4899',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  eventDetails: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  eventDetailText: {
    color: '#a1a1aa',
    fontSize: 12,
    backgroundColor: '#23232b',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  loadingText: {
    color: '#a1a1aa',
    fontSize: 16,
    marginTop: 12,
  },
  
  // Modal Styles
  modalContainer: {
    flex: 1,
    backgroundColor: '#18181b',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#23232b',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
  },
  modalCloseButton: {
    fontSize: 24,
    color: '#a1a1aa',
    fontWeight: 'bold',
  },
  modalContent: {
    flex: 1,
  },
  modalImage: {
    width: '100%',
    height: 250,
    backgroundColor: '#23232b',
  },
  modalEventContent: {
    padding: 20,
  },
  modalEventHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  modalEventTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
    flex: 1,
    marginRight: 16,
  },
  modalEventCategory: {
    backgroundColor: '#6366f1',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  modalEventCategoryText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },
  modalEventDescription: {
    color: '#e5e7eb',
    fontSize: 16,
    lineHeight: 24,
    marginBottom: 24,
  },
  modalEventDetails: {
    marginBottom: 24,
  },
  modalDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  modalDetailIcon: {
    fontSize: 16,
    marginRight: 12,
    width: 24,
  },
  modalDetailText: {
    color: '#e5e7eb',
    fontSize: 16,
    flex: 1,
  },
  bookButton: {
    backgroundColor: '#ec4899',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    alignItems: 'center',
  },
  bookedButton: {
    backgroundColor: '#10b981',
  },
  bookButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
});


export default styles;